name: Deploy to GitHub Pages

on:
  workflow_dispatch:
  push:
    branches:
    - master

permissions:
  contents: write

jobs:
  deploy-to-github-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-dotnet@v5
        with:
          dotnet-version: '10.0.x' 
          
      - name: Publish WebAssembly project
        run: dotnet publish MaterialTheming.Pages -c Release -o release

      # GitHub Pages routing and MudBlazor's _content folder
      - name: Fix GitHub Pages routing and Jekyll issues
        run: |
          touch release/wwwroot/.nojekyll
          cp release/wwwroot/index.html release/wwwroot/404.html

      # Push publish result to gh-pages branch
      - name: Commit and Push to gh-pages branch
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: release/wwwroot